version: '3.4'

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 5000:5000
  identityapi:
        image: api/identityapi
        build:
            context: .
            dockerfile: Identity.API/Dockerfile
        ports:
            - 7001:7001

        

